
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  
  host: <%= ENV['DB_HODT']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>

development:
  <<: *default
  database: cookbook_development

 
test:
  <<: *default
  database: cookbook_test

production:
  <<: *default
  database: cookbook_production
  # url: <%= ENV['DATABASE_URL']%>
  
